# Generated by Django 4.0.3 on 2023-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carrera', models.CharField(max_length=100)),
                ('Edad', models.CharField(max_length=200)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('R1', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R3', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R4', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R5', models.CharField(choices=[('PedidosYa', 'PedidosYa'), ('Yaigo/Yumy', 'Yaigo/Yumy'), ('Uber_eats', 'Uber_eats'), ('PatioServis', 'PatioServis'), ('Otros', 'Otros'), ('Ninguno_de_los_anteriores', 'Ninguno_de_los_anteriores')], max_length=100)),
                ('R6', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R7', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('R8', models.CharField(choices=[('Farmacias', 'Farmacias'), ('Encargos', 'Encargos'), ('Supermercados', 'Supermercados'), ('Restaurantes', 'Restaurantes'), ('Otros', 'Otros'), ('Ninguno_de_los_anteriores', 'Ninguno_de_los_anteriores')], max_length=100)),
                ('R9', models.CharField(max_length=1000, null=True)),
                ('R10', models.CharField(max_length=1000)),
                ('Nombre', models.CharField(max_length=200, null=True)),
                ('Numero_de_Celular', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
